version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/work
  web:
    build: ./infra/nginx
    ports:
      - 10081:80
    volumes:
      - ./src:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  mysql:
    build: ./infra/mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-store:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - 60379:6379
    volumes:
      - redis-store:/data

volumes:
  mysql-store:
  redis-store:
